apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proj-olympus-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/ak-techo/test-argocd-team-a.git'
      path: dataset-chart
      targetRevision: main
      helm:
        values: |
          providerConfigName: boot-gcp-key
          namespace: default

          bigQueryDatasets:
          - name: crosstest
            datasetId: crosstest
            location: us-central1
            projectId: vonage-internal-playground
    - repoURL: 'https://github.com/ak-techo/test-argocd-team-a.git'
      path: sub-chart
      targetRevision: main
      helm:
        values: |
          providerConfigName: boot-gcp-key
          namespace: default

          subnets:
            - subnetName: "test-subnet-two"
              networkSelector:
                matchLabels:
                  network-name: test-vpc
              ipCidrRange: "10.120.1.0/20"
              region: "us-east1"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s