apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proj-olympus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/ak-techo/test-argocd-team-a.git'
      path: dataset-chart
      targetRevision: main
      helm:
        values: |
          providerConfigName: boot-gcp-key
          namespace: default

          bigQueryDatasets:
          - name: test_argo2
            datasetId: test_argo2
            location: us-central1
            projectId: vonage-internal-playground
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s