resources:
  providerConfigName: boot-gcp-key
  namespace: default

  subnets:
    - subnetName: "test-subnet-one"
      networkSelector:
        matchLabels:
          network-name: test-vpc
      ipCidrRange: "10.120.0.0/20"
      region: "us-central1"