apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proj-dash
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ak-techo/test-argocd-team-a.git'
    path: sub-chart
    targetRevision: main
    helm:
      values: |
        providerConfigName: boot-gcp-key
        namespace: default

        subnets:
          - subnetName: "test-subnet-one"
            networkSelector:
              matchLabels:
                network-name: test-vpc
            ipCidrRange: "10.120.0.0/20"
            region: "us-central1"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s