providerConfigName: team-b-config
namespace: team-b
bigQueryDatasets:
- name: test-argo-one
  datasetId: test_argo1_one
  location: us-central1
  projectId: vonage-internal-playground
  # access:
  # - role: "OWNER"
  #   userByEmail: "test-sa@vonage-internal-playground.iam.gserviceaccount.com"
  # - role: "EDITOR"
  #   userByEmail: "test-sa@vonage-internal-playground.iam.gserviceaccount.com"
- name: test-argo-two
  datasetId: test_argo_two
  location: us-central1
  projectId: vonage-internal-playground
