{{- range .Values.subnets}}
apiVersion: compute.gcp.vonage.com/v1alpha1
kind: Subnetwork
metadata:
  name: {{ .subnetName }}
  namespace: {{ $.Values.namespace }}
  labels: 
  {{- range $key, $value := .labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  providerConfigRef:
    name: {{ $.Values.providerConfigName }}
  ipCidrRange: {{ .ipCidrRange }}
  subnetName: {{ .subnetName }}
  region: {{ .region }}
  {{- if .secondaryIpRange }}
  secondaryIpRange:
  {{- range .secondaryIpRange }}
    - rangeName: {{ .rangeName }}
      ipCidrRange: {{ .ipCidrRange }}
  {{- end}}
  {{- end}}
  {{- if .logConfig }}
  logConfig:
  {{- range .logConfig }}
      aggregationInterval: {{ .aggregationInterval }}
      filterExpr: {{ .filterExpr }}
      flowSampling: {{ .flowSampling }}
      metadata: {{ .metadata }}
      metadataFields:
      {{- range .metadataFields }}
        - {{ . }}
      {{- end }}
  {{- end}}
  {{- end}}
  {{- if .networkSelector }}
  networkSelector:
    matchLabels:
    {{- range $key, $value := .networkSelector.matchLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  {{- if .network }}
  network: {{ .network }}
  {{- end }}
  {{- if .description }}
  description: {{ .description }}
  {{- end }}
  {{- if .externalIpv6Prefix }}
  externalIpv6Prefix: {{ .externalIpv6Prefix }}
  {{- end }}
  {{- if .ipv6AccessType }}
  ipv6AccessType: {{ .ipv6AccessType }}
  {{- end }}
  {{- if .project }}
  project: {{ .project }}
  {{- end }}
  {{- if .role }}
  role: {{ .role }}
  {{- end }}
  {{- if .purpose }}
  purpose: {{ .purpose }}
  {{- end }}
  {{- if .stackType }}
  stackType: {{ .stackType }}
  {{- end }}
  {{- if .privateIpGoogleAccess }}
  privateIpGoogleAccess: {{ .privateIpGoogleAccess }}
  {{- end }}
  {{- if .privateIpv6GoogleAccess }}
  privateIpv6GoogleAccess: {{ .privateIpv6GoogleAccess }}
  {{- end }}

---
{{- end }}
